Урок 13 выполнен
Roma-uuu/codeby-devops pull request #15
Opened 2024-08-05 19:29 UTC by Roma-uuu

2024-08-05 19:36 UTC, raguzin requested changes
В целом верно, хотя и очень просто.
лучше такски для разных ОС разнести по разным файлам, н-р debian.yml redhat.yml
а в main выполнять include нужного файла в зависимости от ansible_facts

и что подразумевается под переменной {{ ansible_service_mgr }} ?

2024-08-05 19:59 UTC, Roma-uuu commented
> В целом верно, хотя и очень просто. лучше такски для разных ОС разнести по разным файлам, н-р debian.yml redhat.yml а в main выполнять include нужного файла в зависимости от ansible_facts
> 
> и что подразумевается под переменной {{ ansible_service_mgr }} ?

Можно было не использовать эту переменную, если бы у ОС были разные пакетные менеджеры - в таком случае она бы мне пригодилась. Это чтобы плейбуки подходили под разные ОС.

2024-08-06 19:51 UTC, raguzin commented
а что переменная возвращает? и что должна выполнить эта задача?
- name: Ensure Apache is running
     service:
       name: "{{ ansible_service_mgr }}"
       state: started
       enabled: yes

2024-08-07 06:51 UTC, Roma-uuu commented
> В целом верно, хотя и очень просто.
> 
> лучше такски для разных ОС разнести по разным файлам, н-р debian.yml redhat.yml
> 
> а в main выполнять include нужного файла в зависимости от ansible_facts
> 
> 
> 
> и что подразумевается под переменной {{ ansible_service_mgr }} ?

Упрощается определение какой менеджер служб используется на целевой системе, можно не указывать пакеты и сервисы для разных ОС.
Или я не так понимаю вопрос?

2024-08-07 06:59 UTC, Roma-uuu commented
> а что переменная возвращает? и что должна выполнить эта задача?
> 
> - name: Ensure Apache is running
> 
>      service:
> 
>        name: "{{ ansible_service_mgr }}"
> 
>        state: started
> 
>        enabled: yes

Возвращает имя системы управления сервисами на целевом хосте.
Сейчас эта задача ничего не выполняет, нужно указать имена сервисов.

2024-08-07 08:23 UTC, Roma-uuu commented
Нужно переделать плейбук?

2024-08-07 19:34 UTC, raguzin commented
вот о том и речь, что сейчас эта задача ничего не выполняет - name: Ensure Apache is running
а по идеи необходимо запустить|рестартовать сервис апача.

да, нужно исправить плейбук

2024-08-13 05:46 UTC, Roma-uuu commented
Понял, исправил

2024-08-13 19:32 UTC, raguzin approved these changes
принято

2024-08-13 19:33 UTC, merged